"""empty message

Revision ID: 05e517f8e887
Revises: a1fec6ee23ee
Create Date: 2018-06-29 15:03:56.032169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e517f8e887'
down_revision = 'a1fec6ee23ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'report', ['report_id'], ['id'])
    op.add_column('report', sa.Column('attendance', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('dbspartnership', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('igas', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('newdbs', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('newentrants', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numdbs', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('numloansback', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('numloanstaken', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('numnewdbs', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('otherministries', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('salestracking', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('saving', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('schministries', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('trainings', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'report', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'trainings')
    op.drop_column('report', 'schministries')
    op.drop_column('report', 'saving')
    op.drop_column('report', 'salestracking')
    op.drop_column('report', 'otherministries')
    op.drop_column('report', 'numnewdbs')
    op.drop_column('report', 'numloanstaken')
    op.drop_column('report', 'numloansback')
    op.drop_column('report', 'numdbs')
    op.drop_column('report', 'newentrants')
    op.drop_column('report', 'newdbs')
    op.drop_column('report', 'igas')
    op.drop_column('report', 'dbspartnership')
    op.drop_column('report', 'attendance')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
