"""empty message

Revision ID: 576aac6b2c65
Revises: f7e1cde10395
Create Date: 2018-06-20 16:45:08.124995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576aac6b2c65'
down_revision = 'f7e1cde10395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('donorbond', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('education', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('homevisit', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('lifeskill', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('livelihood', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numhomevisit', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('pss', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('spiritual', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'report', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'spiritual')
    op.drop_column('report', 'pss')
    op.drop_column('report', 'numhomevisit')
    op.drop_column('report', 'livelihood')
    op.drop_column('report', 'lifeskill')
    op.drop_column('report', 'homevisit')
    op.drop_column('report', 'education')
    op.drop_column('report', 'donorbond')
    # ### end Alembic commands ###
