"""bsreport

Revision ID: 678d58745a5f
Revises: 7c60db159bf1
Create Date: 2018-06-13 17:19:12.009533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678d58745a5f'
down_revision = '7c60db159bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('pss', sa.String(length=60), nullable=True),
    sa.Column('livelihood', sa.String(length=60), nullable=True),
    sa.Column('spiritual', sa.String(length=60), nullable=True),
    sa.Column('homevisit', sa.String(length=60), nullable=True),
    sa.Column('donorbond', sa.String(length=60), nullable=True),
    sa.Column('lifeskill', sa.String(length=60), nullable=True),
    sa.Column('achieved', sa.String(length=60), nullable=True),
    sa.Column('challenge', sa.String(length=60), nullable=True),
    sa.Column('othernote', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cep_report_timestamp'), 'cep_report', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cep_report_title'), 'cep_report', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cep_report_title'), table_name='cep_report')
    op.drop_index(op.f('ix_cep_report_timestamp'), table_name='cep_report')
    op.drop_table('cep_report')
    # ### end Alembic commands ###
