"""users table

Revision ID: 6d5b54a11da2
Revises: ac8f050003dc
Create Date: 2018-06-11 20:50:16.756463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5b54a11da2'
down_revision = 'ac8f050003dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_user_role'), 'user', ['user_role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_role'), table_name='user')
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###
