"""empty message

Revision ID: 7418a5df7073
Revises: b3eb36834c7c
Create Date: 2018-06-17 13:45:28.973102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7418a5df7073'
down_revision = 'b3eb36834c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bs_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cep_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'cep_report', type_='foreignkey')
    op.drop_constraint(None, 'bs_report', type_='foreignkey')
    # ### end Alembic commands ###
