"""reports table

Revision ID: ac8f050003dc
Revises: 3cd80e318cce
Create Date: 2018-06-09 11:38:01.675816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8f050003dc'
down_revision = '3cd80e318cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_body'), 'report', ['body'], unique=False)
    op.create_index(op.f('ix_report_timestamp'), 'report', ['timestamp'], unique=False)
    op.create_index(op.f('ix_report_title'), 'report', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_title'), table_name='report')
    op.drop_index(op.f('ix_report_timestamp'), table_name='report')
    op.drop_index(op.f('ix_report_body'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
