"""empty message

Revision ID: bffd6f3a0f74
Revises: 69ee8ddaf0ef
Create Date: 2018-06-17 11:31:59.729084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bffd6f3a0f74'
down_revision = '69ee8ddaf0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bs_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cep_report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.drop_index('ix_user_name', table_name='user')
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'cep_report', type_='foreignkey')
    op.drop_constraint(None, 'bs_report', type_='foreignkey')
    # ### end Alembic commands ###
