"""bsreport

Revision ID: c511756f621a
Revises: 678d58745a5f
Create Date: 2018-06-13 17:26:14.671708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c511756f621a'
down_revision = '678d58745a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bs_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('numschool', sa.String(length=60), nullable=True),
    sa.Column('numstud', sa.String(length=60), nullable=True),
    sa.Column('student', sa.String(length=60), nullable=True),
    sa.Column('numchurch', sa.String(length=60), nullable=True),
    sa.Column('church', sa.String(length=60), nullable=True),
    sa.Column('numfollowup', sa.String(length=60), nullable=True),
    sa.Column('notesfollowup', sa.String(length=60), nullable=True),
    sa.Column('achieved', sa.String(length=60), nullable=True),
    sa.Column('challenge', sa.String(length=60), nullable=True),
    sa.Column('othernote', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bs_report_timestamp'), 'bs_report', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bs_report_title'), 'bs_report', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bs_report_title'), table_name='bs_report')
    op.drop_index(op.f('ix_bs_report_timestamp'), table_name='bs_report')
    op.drop_table('bs_report')
    # ### end Alembic commands ###
