"""empty message

Revision ID: cde593eef324
Revises: 05e517f8e887
Create Date: 2018-06-29 18:37:24.607868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde593eef324'
down_revision = '05e517f8e887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'report', ['report_id'], ['id'])
    op.add_column('report', sa.Column('activities', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('childdiet', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('childhealth', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('childphysicalhealth', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('childsanitation', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('fostercare', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('implementation', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('legalsupport', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numchild', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('policies', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('resettlement', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('security', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'report', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'security')
    op.drop_column('report', 'resettlement')
    op.drop_column('report', 'policies')
    op.drop_column('report', 'numchild')
    op.drop_column('report', 'legalsupport')
    op.drop_column('report', 'implementation')
    op.drop_column('report', 'fostercare')
    op.drop_column('report', 'childsanitation')
    op.drop_column('report', 'childphysicalhealth')
    op.drop_column('report', 'childhealth')
    op.drop_column('report', 'childdiet')
    op.drop_column('report', 'activities')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
