"""empty message

Revision ID: f7e1cde10395
Revises: 7418a5df7073
Create Date: 2018-06-20 12:47:33.576300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7e1cde10395'
down_revision = '7418a5df7073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bs_report', 'user_id')
    op.drop_column('cep_report', 'user_id')
    op.add_column('report', sa.Column('achieved', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('challenge', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('church', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('notesfollowup', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numchurch', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numfollowup', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('numschool', sa.Text(), nullable=True))
    op.add_column('report', sa.Column('numstud', sa.Text(), nullable=True))
    op.add_column('report', sa.Column('othernote', sa.String(length=60), nullable=True))
    op.add_column('report', sa.Column('student', sa.String(length=60), nullable=True))
    op.drop_index('ix_report_body', table_name='report')
    op.create_foreign_key(None, 'report', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'])
    op.drop_column('report', 'body')
    op.create_foreign_key(None, 'user', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('report', sa.Column('body', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_index('ix_report_body', 'report', ['body'], unique=False)
    op.drop_column('report', 'student')
    op.drop_column('report', 'othernote')
    op.drop_column('report', 'numstud')
    op.drop_column('report', 'numschool')
    op.drop_column('report', 'numfollowup')
    op.drop_column('report', 'numchurch')
    op.drop_column('report', 'notesfollowup')
    op.drop_column('report', 'department_id')
    op.drop_column('report', 'church')
    op.drop_column('report', 'challenge')
    op.drop_column('report', 'achieved')
    op.add_column('cep_report', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bs_report', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
